name: release-please
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Placeholder: enable when you actually want automated releases.
      # - name: Release Please
      #   uses: google-github-actions/release-please-action@v4
      #   with:
      #     release-type: go
      #     package-name: wemeet-server
